### PR TITLE
Update postgresql-client, postgresql-server-dev to PG13

### LINKED ISSUE #187: Postgres 13
Now that [Postgres 13 is generally available on Heroku](https://devcenter.heroku.com/changelog-items/2022), do the postgres client binaries need to be updated?

We are having an issue with Heroku CI builds failing due to a version mismatch when restoring from a Rails `structure.sql` file:
```bash
pg_dump: error: server version: 13.1 (Ubuntu 13.1-1.pgdg20.04+1); pg_dump version: 12.5 (Ubuntu 12.5-1.pgdg20.04+1)
       pg_dump: error: aborting because of server version mismatch
       rake aborted!
       failed to execute:
       pg_dump --schema-only --no-privileges --no-owner --file /app/db/structure.sql
```

This pull request updated the client binaries to Postgres 12: https://github.com/heroku/stack-images/pull/151

Is something similar needed to support Postgres 13?

### PR DESCRIPTION
**Pull request by jarydkrish**
Essentially a copy of https://github.com/heroku/stack-images/pull/151, but for Postgres 13 and applied to the Heroku-16, 18, and 20 stacks.

Feel free to close if there's something wrong with this PR - I'm not quite sure how to test it!

Closes #187

### CODE REVIEW

**Comment by edmorley** [comment]
@jarydkrish Hi! Thank you for the PR :-)

The failing Travis CI run for Cedar-14 is just since for that stack (only) we use the ESM (extended maintenance release) APT repository, which requires credentials, and credentials aren't exposed to CI runs of PRs originating from forks. I'll open a non-fork PR now to trigger a CI run (which should also update the CI status here, since GitHub only differentiates by SHA not by branch for the status API).

**Review by edmorley — APPROVED** [review]
The tests triggered by #189 are passing.

Looking at the client-specific parts of the PG13 changelog (https://www.postgresql.org/docs/13/release-13.html#id-1.11.6.6.5.10) I don't see anything too risky.

I'll merge this now, and release a new stack image next week. (We try to avoid releasing stack image updates on a Friday since it can be up to 24 hours before all dynos pick up the new image via the daily restarts, which would take it into the weekend.)

**Comment by edmorley** [comment]
Thank you again for the PR :-)

**Comment by jarydkrish** [comment]
Thanks!

**Pull request merged**
