### PR TITLE
Upgrade postgresql client to 10

### PR DESCRIPTION
**Pull request by dmathieu**
cc @keiko713 @heroku/dod-core

### CODE REVIEW

**Comment by camillebaldock** [comment]
@dmathieu thank you!!! any ETA on when you are hoping to push this?

**Comment by dmathieu** [comment]
@ojacobson could you review this?

**Comment by camillebaldock** [comment]
@dmathieu hi! has this been rolled out to new runtime images yet? :)

**Comment by dmathieu** [comment]
@camillebaldock we have @ojacobson shipping it today :)

**Comment by camillebaldock** [comment]
@dmathieu great thank you :)

**Pull request merged**
