### PR TITLE
Add a docker tag in the `heroku/heroku:18.2019-02-12-10.23.22` format.

### PR DESCRIPTION
**Pull request by jabrown85**
This will allow for users greater control over pulling specific images.

Ref: W-5549708

### CODE REVIEW

**Comment by tt** [comment]
Why do we want to allow users pulling a potentially vulnerable image?

**Comment by jabrown85** [comment]
@tt it might be more for us internally during stack image updates/rollback. I can't locate the incident that spawned this request at the moment.

**Comment by jabrown85** [comment]
@tt updated to push to the private repo instead.

**Comment by edmorley** [comment]
> it might be more for us internally during stack image updates/rollback. I can't locate the incident that spawned this request at the moment.

I managed to track this down to [PRB-0005311](https://gus.lightning.force.com/lightning/r/SM_Problem__c/a4QB00000004XODMA2/view).

**Pull request merged**
